### ISSUE TITLE
Naming conflict: otkit vs otkit

### ISSUE THREAD

**Issue by wesww** [opentable/design-tokens#102]
`otkit` name is already taken by this:
https://github.com/opentable/OTKit/
It is confusing to use the otkit name in a new repo called design-tokens while we still have a repo called otkit. Is the other otkit repo still in active use? It hasn't been touched since April 2013.

**Comment by wesww** [comment]
@olarivain would you perhaps happen to know the status of the original otkit repo?

**Comment by karuto** [comment]
@wesww Thanks for submitting an issue. This is interesting, let's investigate to see if the OTKit repo is still in use.

I'm personally ok if people want to change the OTKit prefix... we should do it through a vote if people feel like changing it.

**Comment by karuto** [comment]
I am closing this issue since @mannionaco seems ok with this.
