### ISSUE TITLE
Prettier for CSS

### ISSUE THREAD

**Issue by nickbalestra** [opentable/design-tokens#104]
Note: There seems to be some open issues with prettier when used with css.modules (ie [@value breaks](https://github.com/prettier/prettier/issues/2355) ). Because of that for the moment we are using prettier only to [format js and not CSS](https://github.com/opentable/design-tokens/pull/101). 
Let's keep an eye open and let's get back to this once prettier will support css.modules without having to ignore specific part of the css with prettier ignore comments.

**Comment by karuto** [comment]
Closing this issue as it does not seem like people cared about it enough. Will circle back if issue arises in future.
