### ISSUE TITLE
publishing to ghpages

### ISSUE THREAD

**Issue by lastquestion** [opentable/design-tokens#113]
One thing I noticed, this preassumes `npm run build` ran and also that `origin` is actually `opentable`. I have an `upstream`, so it didn't work until I manually ran it.

I guess `publish` itself already assumes `origin` is `opentable`, so, maybe this isn't really an issue or problem. But it would be nice to have it work or documented so people who wanna publish must have write permissions and origin set correctly.

**Comment by karuto** [comment]
Yes we should at least have this documented. I worked on a fork when I started too, so this was definitely a gotcha. 👍

**Comment by matteofigus** [comment]
I think that when the autopublish will be completed (working on it this sprint) this should be done by automation, so this should go away 👍
