### ISSUE TITLE
Icons as Common.js: yay or nay?

### ISSUE THREAD

**Issue by matteofigus** [opentable/design-tokens#144]
After discussing with @antwhite and many other stakeholders, I realised that having the icon exported as common.js is possibly less useful than I originally thought.

These are the reasons:
1) As they are now, the whole icons are available in the token, and when using them in react-land webpack is not gonna be able to do tree shaking. The way to fix it, should be to possibly hook into theo's generated file, and possibly produce individual icons. Example:
```js
import ic_star from `otkit-icons/icons/ic_star.js`;
```
2) If you have multiple icons in the page, having the `<svg>` as markup is less ideal for performance reasons. With css, you can have and reuse a css class multiple times in the page, while with JS a developer could make the mistake of repeating the markup multiple times.

3) @antwhite just made a benchmark with chrome to profile the difference between the 2 approaches and CSS seems to be reasonably faster anyways: https://github.com/opentable/ot-react-ui-components/pull/76#issuecomment-371869109

So, before we work on 1 (which we could totally do), I decided to open this issue to discuss: do we actually want common.js, or should we, once addressed the concerns about css modules (separate issue: #143) just distribute as CSS module? Perhaps this could be a chance to avoid people incurring on the possible issues and avoid doing some unnecessary work.

Vote 👍 or 👎 

/cc @antwhite @lastquestion @karuto @nickbalestra 

PS
If I am missing some valid reasons for distributing the common.js too, please add your comment 🙏

**Comment by lastquestion** [comment]
I think we should distribute as commonjs *in the future* and only if design believes that we should have some set of icons which support *runtime variance*.

For example, if we have icons that should change color depending on user, or disable/enable state, things like this, that can be easily encoded as react components with props that affect the visual of the icon. I think this would be a call for desgn (cc @mannionaco @francesyun) to consider.

Once we do decide - if we decide - that we need it, then I would say we should definitely allow for treeshaking by distributing separate files, and we should only output the path. Given that, we will probably need to heavily customize theo for this specific design token, or just do it ourselves all at once directly in `build-icons.js`.

**Comment by lastquestion** [comment]
This one is "yes, maybe in the future, not now" option. :)

**Comment by nickbalestra** [comment]
Great questions Matteo!

Initially we added common.js format as a way to allow the teams that diverged from using `css-modules` (ie `style-components`) to still be able to consume design-tokens. I would also suggest we try to push standardization a bit further here and only expose css-module format from now on, otherwise we are implicitly telling to people, is ok to diverge from css-module standard, pick your own poison, and not sure this is something we want to encourage at the moment.

So, `yey++` for me

**Comment by matteofigus** [comment]
Who is using styled components? @char1e5 was it your team? Are you using design tokens?

**Comment by char1e5** [comment]
@matteofigus yes, we are using styled components and design tokens in R3.
 In the future, we are willing to switch to css modules and ot react components. 
Both styled components and css modules might exist for a while once we start the migration work.
Current R3 icons from design have a lot of varieties. 
E.g. different colors based on react props ✔️icon , dual colors in the same svg icon and a big set of country flags 🇺🇸 icons, etc. 
Right now, we just use them as react component by svg-react-loader (except flags).
I like @lastquestion ‘s idea to keep this flexibility to each shared components and design and expose them as js files once we resolve customize Theo in the future.
I don’t think we are close enough to consume css icons from R3 yet. 
Yes, I just speak for the future here :-)
