### ISSUE TITLE
Auto publishing does not work for new tokens

### ISSUE THREAD

**Issue by karuto** [opentable/design-tokens#175]
This was discovered in #168. After merging, the newly added token `otkit-ticketing-desktop` did not get published. @nickbalestra @matteofigus 

This also caused subsequent PRs such as #174 to fail because Travis assumed `otkit-ticketing-desktop` was already published and threw errors when trying to install the latest version of it.

**Comment by karuto** [comment]
Is this resolved? @matteofigus asked me to create an issue but the PRs were never linked to this issue, I was told that it worked, and looked like the ticketing token is on [npmjs](https://www.npmjs.com/package/otkit-ticketing-desktop), can someone maybe @nickbalestra update me on the status?

I noticed that the npm package only has @nickbalestra as the collaborator so if anyone other than Nick triggers the publish, what would happen? We may want to add some documentation around that process.

**Comment by matteofigus** [comment]
@karuto let's close. The publish at the moment is on Nick's, but we have a story to migrate the auth token to an opentable user delegated to publish (both github and npm). So, manual publish should be no required anymore.

**Comment by matteofigus** [comment]
yes, until next sprint I guess.
