### ISSUE TITLE
s/fuschia/fuchsia

### ISSUE THREAD

**Issue by mattiaerre** [opentable/design-tokens#255]
maybe it is something you've already noticed but would it be possible to fix `fuschia` w/ `fucsia` or there are reasons why we are not doing it?

https://github.com/opentable/design-tokens/search?q=fuschia&unscoped_q=fuschia

**Comment by lastquestion** [comment]
I think the misspelling slipped through. I am OK with a major bump

**Comment by lastquestion** [comment]
Wait, isn't `fuschia` the corrct spelling?!

**Comment by lastquestion** [comment]
https://en.wikipedia.org/wiki/Fuchsia_(color)

**Comment by mattiaerre** [comment]
Yes you are right it is `fuchsia` but for sure NOT `fuschia` 😅

**Comment by mattiaerre** [comment]
ping @lastquestion

**Comment by karuto** [comment]
@mattiaerre sorry for the delay, but we will resolve this in the PR above. Closing this issue.
