### ISSUE TITLE
Visual Styleguide

### ISSUE THREAD

**Issue by nickbalestra** [opentable/design-tokens#30]
@lindseyhight I was thinking that we could perhaps use the token to build a live visual style guide to be used as reference material. Few ideas that I wanted to bounce here:

- We could use a folder here and simply use github pages so that we don't even have to deploy/publish it.
- It could be very similar to the `invision` docs that the design team is producing
- Perhaps we could use it to replace -> https://brand.opentable.com/ ?

cc @lastquestion

**Comment by nickbalestra** [comment]
cc @mannionaco

**Comment by mannionaco** [comment]
@nickbalestra any idea that supports a common ground for our visual language I am for, we're getting closer and I expect us to be in a good place in the coming weeks

**Comment by francesyun** [comment]
I just saw this 😄

I think using Github pages is a great idea! I've just tested it out a little, seems pretty easy to work with: https://opentable.github.io/design-tokens/

@nickbalestra You cool with us playing around with this in the /docs folder?

**Comment by matteofigus** [comment]
@francesyun sure! Consider this is also one of our Q1 goals, so we plan to work together with you on this :)

**Comment by francesyun** [comment]
We did it! Or, we're doing it! Therefore, closing this issue.
