### ISSUE TITLE
Optimizing SVG icons

### ISSUE THREAD

**Issue by ronniechong** [opentable/design-tokens#337]
I noticed most the SVG icons in the current collection have a series of unused or not optimized meta data. e.g.
` <!-- Generator: Sketch 51.1 (57501) - http://www.bohemiancoding.com/sketch -->`
`<title>Icon/Fill/ic_arrived_fill</title>`
`<desc>Created with Sketch.</desc>`
`<defs></defs>`

Just wondering if we should omit some of them and save a few more bytes on the filesize? 😄

**Comment by lastquestion** [comment]
Yes, it could be omitted or omitted as part of an automated script. I don't know if @karuto wanted to work on this. If not, maybe you can contribute something here. :) 👍
