### ISSUE TITLE
[BUG] Auto release tool published wrong version otkit-icons@5.0.0?

### ISSUE THREAD

**Issue by karuto** [opentable/design-tokens#425]
## Overview
I noticed that on Dec 27, `otkit-icons@5.0.0` was published.

However, right after that it published a previous major's patch version `otkit-icons@4.11.1` and etc.

This is why the icons release are broken now, design tokens is trying to publish `otkit-icons@5.0.0` again but it hit a roadblock because that version is already published.

cc @mannionaco @lastquestion 

## Resolution
I'm working on fixing this and getting icons to release again. I have two proposals:
1. Delete this `otkit-icons@5.0.0` bad release and publish the correct `otkit-icons@5.0.0` again sometime in the near future
2. Keep the `otkit-icons@5.0.0` bad release as-is, and skip to the next major version `otkit-icons@6.0.0`.

I'm leaning towards the second approach because it's safer. I've done tag deletion and republishing before, it is not fun and there isn't much upside to it. According to sifu @lastquestion "numbers are cheap".

## References
https://github.com/opentable/design-tokens/tags

## Screenshots
![image](https://user-images.githubusercontent.com/1095291/53202224-cd98da00-35da-11e9-8637-0042f4dbbe29.png)

**Comment by lastquestion** [comment]
Yes just do #2,  and deprecate the bad version.

This happens when we click merge too fast and two builds go thru Jenkins. What we need to do (and I spent like, 30min - 1 hr trying a few months ago) is to serialize the builds so a build doesn't happen until the one before completes fully.

**Comment by karuto** [comment]
This is resolved by following approach 2. Closing
