### ISSUE TITLE
Unsafe usage of PyYAML yaml.load()

### ISSUE THREAD

**Issue by itiskrishnas** [opentable/design-tokens#495]
The default behavior of PyYAML's yaml.load() method is unsafe and can execute code in yaml files.
yaml.safe_load() should be used instead:https://github.com/yaml/pyyaml/issues/193#issuecomment-457387449

https://github.com/opentable/design-tokens/blob/7a53823bf9efe8f9c06e32fdd895c65e6a88f284/utils/automatic-release/lib/defineVersion/index.js#L20

**Comment by itiskrishnas** [comment]
pull [#2](https://github.com/itiskrishnas/design-tokens/pull/2) will resolve this issue.

**Comment by ronniechong** [comment]
Thank you for bringing this up!
