### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by cbeley** [opentable/design-tokens#51]
Any particular reason we are not using camelCase for variable names?  From what I've seen, most codebase seem to adopt camelCase variable names here.

**Comment by matteofigus** [comment]
I think one of the things we tried to reason about at the beginning, together with Sim (design from UK), Nick, Lin and with Kellen's contribution I believe, was to find a way to make contributions from designers easy. For instance, using github for issuing PRs and thinking about the Designer Experience. I believe this is the reason camel case may not have been picked over the current standard. It is worth noting that when exporting the values for common.js usage, the variables are automatically camel cased by theo (the framework we use for bundling). This is an example of otkit-typography:
```js
module.exports = {
    
    lineHeightMedium: "1.33",
    
    fontSizeMedium: "1.125rem",
    
    fontName: "Brandon Text",
    
    fontWeightMedium: "500",
    
    fontSizeLarge: "1.5rem",
    
    lineHeightLarge: "1.33",
    
    lineHeightXlarge: "1.17",
    
    fontSizeXlarge: "3rem",
    
    fontSizeSmall: "1rem",
    
    lineHeightSmall: "1.5",
    
    fontWeightBold: "bold",
    
    lineHeightXsmall: "1.43",
    
    fontSizeXsmall: "0.875rem",
    
    fontWeightNormal: "normal",
};


```

**Comment by nickbalestra** [comment]
As Matteo pointed out the build system automatically convert to camelcase when needed, ie: in js-land.

Is interesting to notice that such approach to go camelCase comes from higher-level js/react-based projects. Not saying that is a bad thing, but as tokens are way lover-level elements in the design-system and are target-stack agnostics perhaps we should gather a broader set of opinions before making such change here (design tokens won't output only css-modules, but scss, common.js and potentially target android xml format and ios json among others.). Furthermore tokens support both new and legacy systems, where for example dashes based naming was standard.

**Comment by cbeley** [comment]
So, I don't quite understand this trend of having tools making things camelCase.  That seems backwards.  If there's a desire to have it be camelCase and the tool is already doing it, why not just make it camelCase from beginning to end to eliminate any possible confusion?  Though, I guess also don't find doing foo['dash-thing'] that bad if it's that format for a special reason.

However, that's a good point @nickbalestra about considering who is going to digest that.  I guess the main concern is if they are being digested by anything that is case-insensitive, in which case, the dashes are the safer bet.

**Comment by morewry** [comment]
> I guess the main concern is if they are being digested by anything that is case-insensitive, in which case, the dashes are the safer bet.

That's sort of true, but the opposite is sort of true, too. One historical reason why kebab-case dominates in style-land is that the majority of both HTML and CSS are case _insensitive_--**except** for some parts that aren't. For example, some attribute values have case-sensitive caveats. [Class attribute values are one of those](https://stackoverflow.com/questions/12533926/are-class-names-in-css-selectors-case-sensitive). Combined with the XHTML era's switch to all-lowercase HTML, this made all-lowercase class names and selectors the least confusing option. Which, of course, led to mostly using all-lowercase in preprocessors and whatnot for stylistic consistency.

**Comment by lastquestion** [comment]
given @morewry 's comment, and the idea of moderation from #66 , I'm going to close this issue. If anyone thinks that we should discuss this again, please open a new issue and let's follow the moderation process.
