### ISSUE TITLE
Border-radius

### ISSUE THREAD

**Issue by francesyun** [opentable/design-tokens#59]
We are using border-radius: 2px in lots of places: the page nav, call-to-action container, buttons, and timeslots. Should I add it as a token? If so, does it need a new section?

**Comment by matteofigus** [comment]
@francesyun I *personally* think that anything that you as Design department agree about coding into a token, should possibly be a token.

In this specific example, I think we are talking about DRY but also coding this decision into something that's gonna bind how page nav, buttons, timeslot, etc. are spaced. Do you think that as design, this makes sense? If yes, I think we should talk about it. But tbh, as engineer (and possibly consumer of DT) I feel like this decision should be on you and I would be fine with both.

**Comment by morewry** [comment]
My perspective is that if it is used and there is an intent to keep using it, it should be a token.

**Comment by karuto** [comment]
Closing this as there hasn't been any discussions, and everyone participated agreed on the proposal. Let's create an action item for a new token.
