### ISSUE TITLE
Adding additional formats

### ISSUE THREAD

**Issue by morewry** [opentable/design-tokens#63]
If someone wanted to add additional formats beyond the four currently available, what would be the process for doing so? Would it be okay for that person to make a pull request to add the new format and merge it themselves without going through an approval process? If not, what is the approval process?

**Comment by matteofigus** [comment]
@morewry the vision and the direction for this project is something we are discussing this week with design, like @mannionaco @francesyun @nickbalestra and more. If both you and design agree on using design tokens, I would say go for it with some PRs.

**Comment by mannionaco** [comment]
Design is for using Design Tokens, process is still to be vetted out from our side and what design's contributions are/will be.

**Comment by lastquestion** [comment]
I think it's a nice thing to let people view and provide feedback before self-merging, even if you have permissions to do so.

I personally prefer all design tokens for the entire company whether consumer or restaurant to live here. We can even have legacy design values that don't "make sense" (e.g. 5 different versions of button spacing, height, etc.) - we also have `ot-theme` legacy here for restaurant anyway, for example.

**Comment by morewry** [comment]
I get what you're saying, but keep in mind that adds a delay for process and emphasizes some of the points @acolchado and I made about why we might start out _not_ using this repo in https://github.com/opentable/buffet/issues/11.

**Comment by lastquestion** [comment]
@morewry originally, we also did the same thing in consumer. the design tokens were stored locally, but still using the same build system, and we moved them here after testing out the experiment and seeing that it worked well. cc @nickbalestra who was the mastermind behind all of that :)

**Comment by morewry** [comment]
Cool. I think this flips over into the other topic into pull request process now, so closing.
