### ISSUE TITLE
Moderation process proposal

### ISSUE THREAD

**Issue by karuto** [opentable/design-tokens#66]
## Why

Discussions here could go stale without a clearly stated moderation process. 

Threads could stay for months without activities and people wouldn't know who should do what to them. 

I firmly believe we should agree on a moderation process to make future discussions sustainable.

## The problems

1. **We don't know when to decide a discussion thread is enough and a decision should be made.** We could argue about technical trivia without a clear context for weeks.

2. **We don't know who should decide or how should we decide** if we can get over problem #1. No clear process contributes to the hesitation of closing out the discussion.

3. **We don't have a formal process on documenting the discussion results** if we can get over problem #2. If someone new wants to make a PR, that person should not need to dig out and read through every closed issue to figure out the agreed upon paradigms.

## Proposal

Below are my personal proposals, their numbers correspond to the problems above.

1. I propose a 7-day + 3-person rule: a thread should have enough comments to decide in 7 days, and at least 3 people should contribute their opinions. 
 - If a thread can't get 3 people to talk about it, the original poster (OP) should invite people to check it out.
 - I'm flexible on the actual numbers, say, if you think 3 people's too few and you want 5 that's fine.

2. I propose the OP should manage the decision making process.
 - Because obviously OP cares enough about the problem to create the thread. This helps with decentralizing responsibility and encourage autonomy.
 - The actual decision making can be done with the "thumb up / thumb down comments" that people seem to like. OP should write a very short decision in each comment and let thumb ups & downs to decide.
 - We should enforce a minimum number of votes. Say a decision should have at least 3 votes (numbers flexible). Again if a thread can't get enough votes we should invite people.

3. We should have a folder `/docs` to host all the decisions we made.
 - OP should create a PR to add the decision just made to the `/docs/`.
 - I can add links to the `/docs` content in the main README if we agree on this.
 - For spreading awareness, we could also encourage OP to send an email to the web platform community.

## Going forward

All these moderation process could also help improve discussion flow in `buffet` or `ot-react-ui-components`. I'm creating the proposal here because this is a better playground with limited context.

I'm very flexible with the actual implementation as long as we have some sort of end-to-end process set up to moderate issues.

Would love your comments on this @lastquestion @nickbalestra @matteofigus @cbeley @morewry

**Comment by morewry** [comment]
I agree, overall it sounds good to me. I'm not sure 7 days seems enough time given individual team circumstances, but I think we should try it, see how it works out, and retrospect. One thing not entirely clear to me is, would we close issues after 7 days if comments have been solicited but not received? Or is there a grace period? If so, what's the actual deadline? And who moderates? The OP, everyone, a set of specific moderators?

A minor thought: I don't think all decisions will be suited to documentation topics, like in cases where someone suggests an idea and we decide not to. Instead of, say, having a documentation page that tracks all vote issues, I'd suggest labeling issues that have votes, so that they can be searched--maybe even labeling with the result of the vote at the time the discussion closed? Labels like "vote" and "vote passed" would help manage issue history.

I'd also suggest having a policy for necroing, one way or the other. A suggestion that isn't worthwhile when originally proposed may become more relevant later.

**Comment by karuto** [comment]
> would we close issues after 7 days if comments have been solicited but not received?

Yeah that is the idea. Like, if a thread can't even get people to care enough to write a comment it is probably not worth arguing about. Details this trivial can just be implemented as you like. If someone complains in your PR you can point to the dead issue be like "hey I mentioned it last time but nobody said anything".

> And who moderates? The OP, everyone, a set of specific moderators?

My suggestion is primarily on OP, community moderators could help by pinging the OP reminding him to follow up instead of doing the work for OP.

> I'd suggest labeling issues that have votes, so that they can be searched

Yes big fan of labeling. Think you set a great example of label usage in buffet. We can have consistent labels and also a doc for the ones suitable to be documented.

> necroing

I think if a problem need to be talked about again we should get a new thread and link to the old thread, instead of commenting under an old thread. Ideally the old thread should be closed thus it has very poor visibility which is not good for new discussions.

**Comment by morewry** [comment]
Sounds good. One more thought, we should summarize this in the ISSUE_TEMPLATE of any repo following the policy.

**Comment by nickbalestra** [comment]
Like the approach @karuto. I digg @morewry 
> try it, see how it works out, and retrospect

**Comment by karuto** [comment]
@morewry @nickbalestra I start to enforce the "7-day, 3-people, 3-vote minimum to conclude" rule with all the issues created after this proposal. 

Do you guys have opinion on what should we do with the previous ones? My suggestion is to treat them equally as if they are new. If you guys are ok with this, I'm going to go through each open issue, tell people that it will be conclude it in 7 days with the same ruleset.

**Comment by morewry** [comment]
Potential tools for later:

https://github.com/bstriner/github-bot-close-inactive-issues
https://github.com/probot/stale

**Comment by lastquestion** [comment]
Do the same thing

**Comment by karuto** [comment]
@morewry Thanks for the suggestion, I will definitely look into them. I'm only doing this manually for the first round... I hope 🤣

**Comment by morewry** [comment]
Yes, I assumed it would be manual for a while, but might eventually be something to automate. That's why I said, "for later."

**Comment by karuto** [comment]
Closing this as we reached agreement.
