### ISSUE TITLE
Excessive Aliasing & What We Should Do About It

### ISSUE THREAD

**Issue by cbeley** [opentable/design-tokens#68]
So, right now, we are aliasing *everything* in `aliases.yml`.  This is a bit confusing.

I propose we only move things into `aliases.yml` if and only if the value needs to be shared.  Otherwise, it should be inlined in the `token.yml` file, so it's very clear what the values are for the given token file.

If, down the road, it needs to be shared, then you can move it into `aliases.yml`.

Vote with the two posts below this, and let's chat about why this may or may not be a good/bad idea. :)

**Comment by cbeley** [comment]
Thumbs up this if you think we should only add things to alias.yml if and only if a value is used in more than one place.

**Comment by cbeley** [comment]
**Thumbs up** this if you think we should continue the current pattern of putting all raw values in `alias.yml`.

**Comment by karuto** [comment]
I support the idea of only putting values that need to be shared among multiple tokens into aliases.

Please vote if you care about this issue. If a comment has more than 3 votes, we will conclude this issue 7 days after its opening, on Nov 8th 2017 in US time. This is based on our moderation proposal in #66.

**Comment by cbeley** [comment]
@karuto Assuming we don't take the functional color names approach, I think the point may be a bit moot.  I would expect shared values to be on the rarer side.

**Comment by cbeley** [comment]
I'd say we can just clean it up in one big ticket.  Should be fairly quick to do.

I could probably find some time for it in my next sprint even.   Better to do it now than later before things get too crazy.

**Comment by matteofigus** [comment]
Before doing this, I would like some input from design. All the thumbs up are from engineers - just want to be sure @mannionaco @francesyun @lindseyhight have seen this thread?

**Comment by matteofigus** [comment]
@cbeley we just had a quick meeting with @francesyun and other designers, and discovered the engineering naming wasn't super inclusive for designers. Can we include a little example of a change, so they can contribute to the conversation? 👍

**Comment by cbeley** [comment]
I got this scheduled for my coming sprint: https://opentable.atlassian.net/browse/MW-2038 .

As for example, see https://github.com/opentable/design-tokens/blob/master/OTKit/otkit-typography/token.yml#L31 .  See how, instead of the value being there, it's actually in https://github.com/opentable/design-tokens/blob/master/OTKit/aliases.yml#L78 .  With the proposed change, we'll inline it, so in token.yml, it looks like:

```
line-height-xlarge:
    type: "size"
    value: "48px"
```

Things will only go in aliases.yml if there are aliases we need to share in multiple places.

I'll just chat with them in person real quick here to double check they understand.

**Comment by karuto** [comment]
Just FYI @cbeley the example you linked, the value of `line-height-xlarge` is actually shared across other tokens such as https://github.com/opentable/design-tokens/blob/master/OTKit/otkit-desktop-typography/token.yml#L8.

I am generally supporting the "inline all the isolated values" approach, but we have to be mindful about which variables are shared.

**Comment by cbeley** [comment]
Take a look at https://github.com/opentable/design-tokens/pull/73 .

**Comment by cbeley** [comment]
I think the PR pretty much covers this now, so I'll go ahead and close this issue.
