### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by karuto** [opentable/design-tokens#69]
## Let's face it. Our current documentation sucks.

...and I'm not blaming anyone because I wrote most of them myself.

I was helping @tpgmartin to publish a token and witnessed the pain first-hand. We got lots of room to improve:

1. **Duplicates.** There is no reason for [OTKit](https://github.com/opentable/design-tokens/blob/master/OTKit/README.md) and [OTTheme](https://github.com/opentable/design-tokens/blob/master/OTTheme/README.md) to have almost identical docs. Besides the list of tokens there are no workflow differences in the 2 folders. This ain't DRY and we already see the problem of forgetting to update the OTTheme docs.
 - Proposal: let's just merge them into the main README.

2. **Confusing entry point.** The main [README](https://github.com/opentable/design-tokens/blob/master/README.md) tells you basically nothing helpful, based on the experiences of Tom, Frances and more. The main docs should be the single central hub that contain everything you need to know from installing, debugging, publishing, contributing and more. 
 - Proposal: consolidate and move all the helpful content from the folder docs into the main README.
 - Proposal: continue to work with designers to make sure our language and terminology is approachable and friendly to everyone in the documentations.

3. **Publishing.** Right now the publishing process is tricky: you need to manually change `.npmrc`, make sure you are added on NPM as collaborator, then run publish command individually. @nickbalestra and @matteofigus have [ideas](https://github.com/opentable/design-tokens/pull/49#discussion_r143261083) on how to improve this. I would love to have per token registry so we don't have to jump through all the loops. Related to documentation, let's just have a single table of token versions in the main README instead of having 3 tables in 3 places.
 - Proposal: add per token registry.
 - Proposal: have a single table to list all token versions in the main README.

I can create PRs for all them once we agree. But would like everyone's input. @nickbalestra @matteofigus @lastquestion @morewry @tpgmartin @cbeley @francesyun.

Please vote if you care about this issue. If a comment has more than 3 votes, we will conclude this issue 7 days after its opening, on Nov 11th 2017 in US time. This is based on our moderation proposal in #66.

**Comment by karuto** [comment]
Thumb up if you agree we should merge the OTKit and OTTheme README into the main one. Thumb down if you disagree.

**Comment by karuto** [comment]
Thumb up if you agree our current README is not friendly enough to designers and people unfamiliar with the project, and we should work on it. Thumb down if you disagree.

**Comment by karuto** [comment]
Thumb up if you agree we should add npm registry per token in the config. Thumb down if you disagree.

**Comment by karuto** [comment]
Ok I'm a little bit unsure about the "add npm registry per token" one, because I believe we should control this at the entire project level instead of per token. But I don't have enough research to back myself up. Chime in @matteofigus @nickbalestra?

**Comment by matteofigus** [comment]
I made a PR for the 3rd point @karuto: https://github.com/opentable/design-tokens/pull/70 I think that just publishing now should work - each module should go to public. That's what we want right?

**Comment by karuto** [comment]
We have now merged #76 as a result of this issue, I'm closing.
