### ISSUE TITLE
Wrong alias for `subtext-xsmall-font-weight-alternate` for otkit-desktop-typography

### ISSUE THREAD

**Issue by ericz82** [opentable/design-tokens#90]
Despite the token being defined as 
```
subtext-xsmall-font-weight-alternate:
    type: "raw"
    value: "{!font-weight-normal}"
```
 in token.yml, the value shows up in token.cssmodules.css as
```
@value subtext-xsmall-font-weight-normal: normal;
```

Same thing is true for `heading-large-font-weight-alternate`.

@karuto Since you were the one who did most of the refactoring, maybe you have a clue on what is happening?

**Comment by karuto** [comment]
I'm not clear what you are asking.

> in token.yml, the value shows up in token.cssmodules.css as `@value subtext-xsmall-font-weight-normal: normal;`

I can't find this variable, what do you mean? This variable does not exist in the token, do you mean `subtext-xsmall-font-weight-alternate`?

If you are talking about `subtext-xsmall-font-weight` then it should compile to the value of `{!font-weight-medium}` which is 500.

**Comment by ericz82** [comment]
If you look in your `node_modules` under `otkit-desktop-typography`, the alias reads as `subtext-xsmall-font-weight-normal`

**Comment by karuto** [comment]
I see, this is likely an outdated variable issue, I will fix it tomorrow. Good catch!

**Comment by ericz82** [comment]
@karuto Any updates on this yet?

**Comment by lastquestion** [comment]
@karuto can you investigate and close this out? it's so old I think we must have fixed it already.

**Comment by karuto** [comment]
@ericz82 @lastquestion yes this is confirmed to be fixed in the latest version of `otkit-desktop-typograph` token, it's a legacy issue.
